server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10
  write_timeout: 10
  shutdown_timeout: 10

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "myapp"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  expire_hour: 24

logger:
  level: "info"
  format: "json"
  output_path: "stdout"

